import { Montserrat } from 'next/font/google';
import './globals.css';
import '@/style/app.scss';

// const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={montserrat.className}>
                <div className="layout-container">
                    <div><p>Header 112</p></div>
                    {children}
                    <div><p>Footer 112</p></div>
                </div>
            </body>
        </html>
    );
}
